defaults:
  - paths: default
  - data: ag_news
  - model: baseline
  - trainer:
    enable_checkpointing: true
    default_root_dir: ${paths.outputs_dir}
  - logging: mlflow
  - _self_

seed: 42
batch_size: 64
lr: 3e-4
max_length: 256
num_workers: 0
